#!/bin/sh

(
    cd """$(dirname "$0")""" || exit 1
    cd ../.git/hooks || exit 1
    for hook_source in ../../git-hooks/*; do
        hook_name=$(basename "$hook_source")
        echo "Linking $hook_name from $hook_source to .git/hooks/$hook_name"
        ln -sf "../../git-hooks/$hook_name" "$hook_name"
    done
)
